development:

  host: localhost
  adapter: postgresql
  encoding: utf8
  database: bacon_jobs_board_development
  pool: 5
  timeout: 5000

test: &TEST
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: bacon_jobs_board_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: bacon_jobs_board_production
  pool: 5
  timeout: 5000

cucumber:
  <<: *TEST
