# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Job.create!(title: "Artisan Jeweler", description: "Our jewelery is crafted in the mokume game-style. Mokume gane is an ancient Japanese technique that bonds numerous layers of precious metals into a single piece that is then worked into beautiful patterns. The name means 'wood-pattern metal'. Mokume gane created by Chris Ploof Designs is fused by traditional methods, using heat and pressure. We don’t buy mokume from other makers, and we don’t rely on solder to hold our layers together. By hand-crafting our mokume, we are able to produce the highest quality rings, second to none. Our unique patterns and designs showcase the natural beauty of the material itself.", company: "Chris Ploof Designs", location: "Nolita, NY", jobtype: "Contractual Work");
Job.create!(title: "Caterer", description: "No matter what your special event is... wedding, anniversary, seasonal party, birthday, bar/bat mitzvah and everything in between, Brent Newsom Caterer is the perfect choice to make sure every aspect of your experience goes exactly as you imagined it. Our staff and services can create any theme and menu you desire. Contact us today for great party ideas and creative answers to your catering needs.", company: "Brent Newsom Caterer", location: "East Hampton, NY", jobtype: "Contractual Work");
Job.create!(title: "Yoga Instructor", description: "Raised on the path of Bhakti Yoga, Dhyana brings the depth of inquisition into her classes, offering opportunities to cultivate a relationship with our multi-faceted humanness while simultaneously taking a step back, a step deeper into the truth of who we really are; beyond the stories, the fears, and the limitations. Having a deep understanding of the nature of the mind and its relationship to the Self, her classes combine non-sectarian yoga philosophy with an integrated experience, sharing timeless Truths in an easy-to-apply and accessible way.", company: "Dhyana Masla Yoga",location: "Lower East Side, NY", jobtype: "Contractual Work");
Job.create!(title: "Locksmith", description: "We have a full service locksmith company servicing commercial, residential, and automotive needs. Our locksmiths are A.L.O.A. certified registered and bonded. We can cut keys by code, rekey locks, install deadbolts, lockouts, safe sales and service and much more. We also have a fully equipped mobile shop.", company: "Johnson's Hardware Shop.",location: "Astoria, NY", jobtype: "Contractual Work");
Job.create!(title: "Web Designer", description: "I'm a classically trained web designer who is well-versed in the latest frontend and backend technologies. I can design and build fully-functional websites from scratch according to the clients' need. My specialty involves integrating dynamic features seamlessly into the user's experience with your product", company: "Freelance",location: "Williamsburg, NY", jobtype: "Contractual Work or Full-time");
Job.create!(title: "Painter", description: "Specializing in: Interior/Exterior Painting, Spackling, Wallpaper Removal, Sheetrock Repair, Tile -
All Phases of Carpentry. Door Installations/Trim Work, Deck Repair, Bathroom Remodeling. Professional, Reliable. Owner on every Job! Over 25 years experienced. Licensed/Insured", company: "Scott Anthony Painting.",location: "Midtown East, NY", jobtype: "Contractual Work");
Job.create!(title: "Landscaper", description: "The Whitmore family has been in the landscaping, nursery and gardening business, serving the Hamptons since 1945. From landscape design and large tree installation and preservation, to providing the highest quality plant materials and year-round maintenance, you won’t find a team with more expertise or local knowledge. Trust Whitmores to enhance the beauty and value of your property.", company: "Whitmores",location: "Carroll Gardens, NY", jobtype: "Full-time");
Job.create!(title: "Plumber", description: "Since 1968, Upper East Side residents have trusted Best Plumbing with all their plumbing needs. Whether it’s helping you with a leaky faucet or you need a top-notch local company to execute your commercial project, Best Plumbing is here for you. ", company: "Best Plumbing",location: "Upper East Side, NY", jobtype: "Contractual Work");
Job.create!(title: "Dog Walker", description: "I'm a university student at Columbia University with a lot of free time and student debt. Let me walk your dog!", company: "Freelance",location: "Washington Heights, NY", jobtype: "Part-time");
Job.create!(title: "Personal Trainer", description: "I'm a former Division I NCAA sprinter and I'm looking to train high-school and college-aged athletes who are looking for a top-class training regimen dedicated to speed, agility, and strength.", company: "Phew-sioneering",location: "Long Island City, NY", jobtype: "Part-time");
